### ISSUE TITLE
Set up website

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#25]
One of the main things that we mean to accomplish with pyviz-topics/examples is a set of stable urls that we can link to from all of our other projects. There should be some minimal index page, but more importantly there need to be static versions of all our topics suitable for iframing and linking. Since many of these topics require large datasets and/or take a long time to run, we will want to build these things locally. I am imagining that this will look a lot like the build process for earthml, where if the project falls under either of those categories (large data or slow to run), the maintainer is responsible for uploading an evaluated version to a specific branch. Then when we use nbsite to build the website on travis, it can grab the evaluated versions from that "blessed" branch first. 

So there should be a command that the maintainer can run locally that will do this evaluation.

I guess there is also another case to think about which is the more-than-one notebook per project case. I think @jbednar's suggestion that we default to the notebook with the same name as the dir is a good one, but we might want to provide a mechanism for overriding that in the anaconda-project.yml.

I will start drafting what this will look like unless anyone has some requirements they'd like to add. @pyviz-topics/pyviz-dev

**Comment by jbednar** [comment]
Instead of (typically) building them locally, can we build them on Travis, but just one at a time, on a specific push or tag?  Building them all as a group would take way too long, including data downloads, but building individual projects doesn't seem infeasible.  That way we could develop on the project locally, commit it, then trigger builds for that particular project until the website is ok, knowing that there's nothing about our local setup that's not captured in the automated setup. 

I think only the OSM 3 billion case wouldn't fit into that plan, and it could be handled using the `evaluated version` approach; the rest seem like they don't need it.

**Comment by jsignell** [comment]
It depends how many downloads we want to have happen on travis. But yeah that seems feasible I hadn't thought of using a specific flag. But I did set up the infrastructure to only run tests on one travis job so it could look a lot like that. We might even be able to cache the data dir.

**Comment by jbednar** [comment]
Sounds good. I think an extra few downloads of the datasets are fine, when explicitly requested, as long as it's not an automated job.
