### ISSUE TITLE
Should test data be mandatory?

### ISSUE THREAD

**Issue by jsignell** [pyviz-topics/examples#72]
@jlstevens and I were talking about test data and how it relates to #70. Currently, travis is configured to fail if a project requires data (either as a download in anaconda-project.yml or via an intake catalog). The idea behind this failure is to make the project author aware that test data should be used when possible. However, this can be kind of annoying if the data are remote, but not very large. 

Perhaps this failure should become a warning instead. I ran into this in #71 as well.

**Comment by jlstevens** [comment]
All I think is needed here is an escape hatch for cases where test data shouldn't be necessary e.g if you needed to add a line to the anaconda-project.yml to declare things that shouldn't need extra test data. Our job would be to make sure it is used appropriately before merging in new examples and we wouldn't encourage the use of this escape hatch unless it is justified.

**Comment by jsignell** [comment]
I think it is probably easier to downgrade to a warning unless someone disagrees.

**Comment by jbednar** [comment]
Personally, I believe we should enforce having test data when the data is remote, because any remote source can disappear or change.  The test data serves as a record of the type of data that the project expects, included directly in the repo in a way that can never get out of sync.  That way if the remote data changes, we can tell that the resulting problems are not due to a change in the software, but in the data.

**Comment by jsignell** [comment]
Fair enough. I am fine with leaving it madatory.
